title: CFK Fellowship

description: >
  Build educational opportunities. Grow with purpose.

url: "https://fellowship.careforknowledge.org"

baseurl: ""

timezone: Africa/Lagos

lang: en

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed