"""
cohort_new.py
─────────────
Sets up everything needed to start a new cohort.

Takes a CSV of new Foundation Fellows and config arguments, then:
  1. Creates _data/[season-year]-fellows.yml
  2. Creates cohorts/[season-year]/index.html
  3. Adds the cohort to _data/cohorts.yml (top of list)
  4. Updates _data/current_cohort.yml
  5. Sets _data/site_status.yml to 'recruiting'

Prints a checklist of what still needs manual attention.

USAGE
  python scripts/cohort_new.py \\
    --name "Spring 2027" --season spring --year 2027 \\
    --fellows new_fellows.csv

  # Dry run — see what would be created without writing anything
  python scripts/cohort_new.py --name "Spring 2027" --season spring --year 2027 \\
    --fellows new_fellows.csv --dry-run

FELLOWS CSV FORMAT
  Required: first_name, last_name, track
  Optional: photo (will default to /assets/images/cohorts/[slug]/[firstname-lastname].jpg)

SEASON VALUES
  spring  →  start month: February
  autumn  →  start month: August
"""

import os
import sys
import csv
import re
import argparse

REPO_ROOT  = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR   = os.path.join(REPO_ROOT, '_data')
COHORTS_DIR = os.path.join(REPO_ROOT, 'cohorts')

try:
    import yaml
except ImportError:
    print("ERROR: PyYAML is not installed. Run: pip install pyyaml")
    sys.exit(1)

sys.path.insert(0, os.path.dirname(__file__))

def clean_text(value):
    """
    Fix common encoding garbling from Google Sheets CSV exports.
    Google Sheets exports UTF-8 without BOM; if read with wrong encoding,
    special characters appear garbled. This fixes the most common cases.
    """
    if not value:
        return value
    # Try to fix UTF-8 bytes misread as latin-1/cp1252
    try:
        fixed = value.encode('latin-1').decode('utf-8')
        return fixed
    except (UnicodeEncodeError, UnicodeDecodeError):
        pass
    # Manual fallback for the most common garbled sequences
    replacements = {
        'â€"': '—',   # em dash
        'â€™': "'",   # right single quote
        'â€˜': "'",   # left single quote
        'â€œ': '"',   # left double quote
        'â€':  '"',   # right double quote
        'â€¦': '…',   # ellipsis
        'Ã©':  'é',
        'Ã¨':  'è',
        'Ã ':  'à',
        'Ã¢':  'â',
        'Ã®':  'î',
        'Ã´':  'ô',
        'Ã»':  'û',
        'Ã§':  'ç',
        'Ã«':  'ë',
        'Ã¯':  'ï',
        'Ã¼':  'ü',
        'Ã¶':  'ö',
        'Ã¤':  'ä',
        'Ã±':  'ñ',
    }
    for garbled, correct in replacements.items():
        value = value.replace(garbled, correct)
    return value

def clean_row(row):
    """Apply clean_text to every value in a CSV row dict."""
    return {k: clean_text(v) if isinstance(v, str) else v for k, v in row.items()}

def normalise_headers(reader):
    """
    Strip asterisks and extra whitespace from CSV column headers.
    This allows headers like 'slug *' or 'first_name *' (used in the
    Google Sheets template as visual hints) to be read as 'slug', 'first_name'.
    """
    reader.fieldnames = [
        f.replace('*', '').strip()
        for f in (reader.fieldnames or [])
    ]
    return reader



from fellow_add import make_slug


def make_cohort_slug(season, year):
    return f"{season.lower()}-{year}"


def write_file(path, content, dry_run=False):
    """Write a file, or print it in dry-run mode."""
    if dry_run:
        print(f"  (DRY RUN) Would write: {os.path.relpath(path, REPO_ROOT)}")
        return
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f"  ✅ {os.path.relpath(path, REPO_ROOT)}")


def create_fellows_list(fellows, cohort_slug, dry_run=False):
    """Create _data/[cohort-slug]-fellows.yml"""
    lines = [
        f'# {cohort_slug}-fellows.yml',
        f'# Foundation Fellows for the {cohort_slug} cohort.',
        f'# Generated by cohort_new.py — edit as needed.',
        f'# When the cohort ends, run cohort_graduate.py to create permanent Fellow pages.',
        '',
    ]
    for f in fellows:
        slug = make_slug(f['first_name'], f['last_name'])
        photo = f.get('photo', '').strip() or f"/assets/images/cohorts/{cohort_slug}/{slug}.jpg"
        lines.append(f'- first_name: "{f["first_name"]}"')
        lines.append(f'  last_name: "{f["last_name"]}"')
        lines.append(f'  track: "{f["track"]}"')
        lines.append(f'  photo: "{photo}"')
        lines.append('')

    path = os.path.join(DATA_DIR, f'{cohort_slug}-fellows.yml')
    write_file(path, '\n'.join(lines), dry_run)
    return path


def create_cohort_page(cohort_slug, cohort_name, dry_run=False):
    """Create cohorts/[cohort-slug]/index.html"""
    content = f"""---
layout: base
title: "{cohort_name} Cohort"
description: "Meet the {cohort_name} CFK Fellowship Foundation Fellows — currently in progress across WikiQuestions, CTRI, Model NASS, and CFK Fellowship."
---

{{% assign cohort_data = site.data.cohorts | where: "slug", "{cohort_slug}" | first %}}
{{% assign fellows = site.data["{cohort_slug}-fellows"] %}}

<header class="page-header">
  <div class="inner page-header-inner">
    <span class="page-eyebrow">CFK Fellowship · <a href="/cohorts/" style="color:var(--cyan);opacity:0.7;">Cohorts</a></span>
    <h1 class="page-title">{{{{ cohort_data.name }}}} Cohort</h1>
    <p class="page-intro">{{{{ cohort_data.date_range }}}} · {{{{ cohort_data.fellow_count }}}} Foundation Fellows · Currently active</p>
    <p class="page-intro" style="margin-top:0.75rem;">{{{{ cohort_data.description }}}}</p>
  </div>
</header>

<main style="padding:4rem 0 6rem;background:var(--white);">
  <div class="inner">
    <div style="font-size:0.72rem;font-weight:700;letter-spacing:0.18em;text-transform:uppercase;color:var(--muted);margin-bottom:2.5rem;">
      Foundation Fellows · In Progress
    </div>
    <div class="cohort-card-grid">
      {{% for person in fellows %}}
      <div class="cohort-card">
        <div class="cohort-card-photo">
          {{% if person.photo and person.photo != "" %}}
            <img src="{{{{ person.photo }}}}" alt="{{{{ person.first_name }}}} {{{{ person.last_name }}}}" loading="lazy" onerror="this.style.display='none';">
          {{% endif %}}
          <span class="cohort-card-initials" aria-hidden="true">{{{{ person.first_name | slice: 0 }}}}{{{{ person.last_name | slice: 0 }}}}</span>
        </div>
        <div class="cohort-card-name">{{{{ person.first_name }}}} {{{{ person.last_name }}}}</div>
        <div class="cohort-card-track">{{{{ person.track }}}}</div>
      </div>
      {{% endfor %}}
    </div>
  </div>
</main>
"""
    path = os.path.join(COHORTS_DIR, cohort_slug, 'index.html')
    write_file(path, content, dry_run)


def update_cohorts_yml(cohort_slug, cohort_name, season, year, fellow_count, dry_run=False):
    """Add the new cohort to the top of _data/cohorts.yml"""
    path = os.path.join(DATA_DIR, 'cohorts.yml')
    with open(path, 'r', encoding='utf-8') as f:
        existing = f.read()

    start_month = 'February' if season.lower() == 'spring' else 'August'
    end_month   = 'May' if season.lower() == 'spring' else 'November'

    new_entry = f"""- name: "{cohort_name}"
  slug: "{cohort_slug}"
  season: "{season.title()}"
  year: "{year}"
  date_range: "{start_month} – {end_month} {year}"
  fellow_count: {fellow_count}
  status: "active"
  founding: false
  description: "The {cohort_name} cohort."
  report_url: ""

"""
    # Insert after the header comments, before the first entry
    if existing.strip().startswith('#'):
        # Find first '- name:' line
        idx = existing.find('- name:')
        if idx >= 0:
            updated = existing[:idx] + new_entry + existing[idx:]
        else:
            updated = existing + '\n' + new_entry
    else:
        updated = new_entry + existing

    if dry_run:
        print(f"  (DRY RUN) Would update: _data/cohorts.yml")
    else:
        with open(path, 'w', encoding='utf-8') as f:
            f.write(updated)
        print(f"  ✅ _data/cohorts.yml (new entry added at top)")


def update_current_cohort_yml(cohort_slug, cohort_name, season, year, fellow_count, dry_run=False):
    """Rewrite _data/current_cohort.yml for the new cohort."""
    start_month = 'February' if season.lower() == 'spring' else 'August'
    end_month   = 'May' if season.lower() == 'spring' else 'November'

    content = f"""# ═══════════════════════════════════════════════════════════════
# CURRENT COHORT
# Updated by cohort_new.py — {cohort_name}
# ═══════════════════════════════════════════════════════════════

name: "{cohort_name}"
season: "{season.title()}"
year: "{year}"
slug: "{cohort_slug}"

start_month: "{start_month}"
end_month: "{end_month}"
full_date_range: "{start_month} – {end_month} {year}"

fellow_count: {fellow_count}

tracks:
  - WikiQuestions
  - CTRI
  - Model National Assembly
  - CFK Fellowship

# ── LINKS ───────────────────────────────────────────────────────
# UPDATE THESE after running this script:
apply_url: ""
waitlist_url: ""

# ── STATUS-SPECIFIC MESSAGES ────────────────────────────────────
recruiting:
  announcement: "Applications for the {cohort_name} Cohort are now open."
  hero_status: "Applications open · {cohort_name} Cohort"
  cta_label: "Apply Now"

reviewing:
  announcement: "Applications for the {cohort_name} Cohort are now closed. We are reviewing applications."
  hero_status: "Applications closed · Selections in progress"
  cta_label: "Join the Waitlist"

active:
  announcement: "The {cohort_name} Cohort is underway."
  hero_status: "{cohort_name} Cohort · Now active"
  cta_label: "Join the Waitlist"

between:
  announcement: "No cohort is currently running. The next cohort will be announced in due course."
  hero_status: "Next cohort coming soon"
  cta_label: "Join the Waitlist"
"""
    path = os.path.join(DATA_DIR, 'current_cohort.yml')
    write_file(path, content, dry_run)


def update_site_status(dry_run=False):
    """Set site status to recruiting."""
    content = "# Updated by cohort_new.py\nstatus: \"recruiting\"\n"
    path = os.path.join(DATA_DIR, 'site_status.yml')
    write_file(path, content, dry_run)


def main():
    parser = argparse.ArgumentParser(description='Set up a new cohort.')
    parser.add_argument('--name',    required=True, help='Full cohort name (e.g. "Spring 2027")')
    parser.add_argument('--season',  required=True, choices=['spring', 'autumn'],
                        help='Season: spring or autumn')
    parser.add_argument('--year',    required=True, help='Year (e.g. 2027)')
    parser.add_argument('--fellows', required=True, help='CSV of new Foundation Fellows')
    parser.add_argument('--dry-run', action='store_true',
                        help='Preview without writing any files.')
    args = parser.parse_args()

    cohort_slug = make_cohort_slug(args.season, args.year)

    csv_path = args.fellows if os.path.isabs(args.fellows) else os.path.join(REPO_ROOT, args.fellows)
    if not os.path.exists(csv_path):
        print(f"ERROR: Fellows CSV not found: {csv_path}")
        sys.exit(1)

    with open(csv_path, 'r', encoding='utf-8-sig') as f:
        reader = csv.DictReader(f)
        normalise_headers(reader)
        headers = reader.fieldnames or []
        for col in ['first_name', 'last_name', 'track']:
            if col not in headers:
                print(f"ERROR: CSV missing required column: '{col}'")
                sys.exit(1)
        fellows = [
            {'first_name': clean_text(r['first_name']).strip(),
             'last_name':  r['last_name'].strip(),
             'track':      r['track'].strip(),
             'photo':      r.get('photo', '').strip()}
            for r in reader
            if r.get('first_name', '').strip()
        ]

    if not fellows:
        print("ERROR: No Fellows found in CSV.")
        sys.exit(1)

    print(f"\nSetting up new cohort: {args.name}")
    print(f"Slug: {cohort_slug}  |  Fellows: {len(fellows)}")
    if args.dry_run:
        print("DRY RUN — no files will be written.\n")
    print()

    create_fellows_list(fellows, cohort_slug, args.dry_run)
    create_cohort_page(cohort_slug, args.name, args.dry_run)
    update_cohorts_yml(cohort_slug, args.name, args.season, args.year, len(fellows), args.dry_run)
    update_current_cohort_yml(cohort_slug, args.name, args.season, args.year, len(fellows), args.dry_run)
    update_site_status(args.dry_run)

    print(f"\n{'─'*55}")
    print(f"✅ Cohort setup {'preview' if args.dry_run else 'complete'}!")
    if not args.dry_run:
        print(f"\n⚠️  STILL TO DO (manually):")
        print(f"  → Add the registration form URL to _data/current_cohort.yml (apply_url)")
        print(f"  → Add the waitlist URL to _data/current_cohort.yml (waitlist_url)")
        print(f"  → Update the cohort description in _data/cohorts.yml")
        print(f"  → Update the announcement messages in _data/current_cohort.yml if needed")
        print(f"  → Upload headshots to assets/images/cohorts/{cohort_slug}/")
        print(f"  → Commit and push to GitHub")
        print(f"\n  Site status is now: recruiting")
        print(f"  Cohort page will be at: /cohorts/{cohort_slug}/")


if __name__ == '__main__':
    main()
